# Strings are immutable(not changable)
x = "as!herMione! !!"
print(len(x))
print(x.upper())
print(x.lower())
print(x.rstrip("!"))
print(x.replace("her", "har"))
print(x.split())
print(x.capitalize())
print(x.center(20))
print(x.endswith("!!!"))
print(x.endswith("one", 8, 11))
print(x.find("her"))
print(x.isalnum())
print(x.isalpha())
print(x.isdigit())
print(x.islower())
print(x.isprintable())
print(x.isspace())
print(x.istitle())
print(x.swapcase())
